<img src="https://dauphine.psl.eu/fileadmin/_processed_/9/2/csm_damier_logo_Dauphine_f7b37a1ff2.jpg" width="200" style="vertical-align:middle" /> <h1>Master 222: Introduction to Python - Session 2</h1>

[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/Zaltarba/PSL_python_for_finance/blob/main/python_session_2_corrected.ipynb)


# Remainders From Last Session

## Temperature Data Analysis

**Introduction**
You're provided with a list of temperatures (in degrees Celsius) spanning over a week:
``` python
temperatures = [20.5, 22.3, 19.8, 21.6, 23.2, 18.9, 20.2]
```
Your task is to analyze this data by developing specific functions and then interpreting the results.

**Functions to Develop**

1.   Function `average_temp()`:

*Input:* A list of temperatures.

*Task:* Calculate the average temperature for the week.

*Return:* The average temperature.

2. Function `hot_days_count()`:

*Input:* A list of temperatures.

*Task:* Determine the number of days the temperature was above 21°C.

*Return:* The count of days.

3. Function `coldest_day()`:

*Input:* A list of temperatures.

*Task:* Identify the index of the coldest day (0 for Monday, 6 for Sunday).

*Return:* The index of the day.

**Display the Results**

After you've developed and tested your functions, you should:

- Print the average temperature of the week.
- Print the number of days when the temperature was above 21°C.
- Print the coldest day of the week based on the index (e.g., "The coldest day was Wednesday...").

**Sample output**
``` python
The average temperature for the week is: 20.79°C.
There were 3 days with a temperature above 21°C.
The coldest day was Wednesday with a temperature of 18.9°C.
```
 
Try using a list by comprehension for question 1 and 2.  
Use a dictionary for the question 3 to map indices to days of the week.

In [1]:
temperatures = [20.5, 22.3, 19.8, 21.6, 23.2, 18.9, 20.2]
## Insert your code here
from typing import List 

def average_temp(temperatures:List[float])->float:
    return sum(temperatures) / len(temperatures)

print(f"The average temperature for the week is: {average_temp(temperatures)}°C")

def hot_days_count(temperatures:list[float])->int:
    return sum([1 if temp > 21 else 0 for temp in temperatures])

print(f"There were {hot_days_count(temperatures)} days with a temperature above 21°C")

index_to_days = {
    0:'Monday', 
    1:'Tuesday', 
    2:'Wednesday', 
    3:'Thursday', 
    4:'Friday', 
    5:'Saturday', 
    6:'Sunday', 
    }

def coldest_day(temperatures):
    min_index = 0
    min_temp = temperatures[0]
    for index, temp in enumerate(temperatures):
        if temp < min_temp:
            min_index = index
            min_temp = temp
    return min_index

min_index = coldest_day(temperatures)
print(f"The coldest day was {index_to_days[min_index]} with a temperature of {temperatures[min_index]} °C")

The average temperature for the week is: 20.928571428571423°C
There were 3 days with a temperature above 21°C
The coldest day was Saturday with a temperature of 18.9 °C


# The NumPy library

## Context and Objective

Python is an almost indispensable programming language in the world of Quantitative finance.   
It's open source, and increasingly popular.  
In this exercise, you will learn to use the NumPy module.  
NumPy is a Python package specialized in the manipulation of arrays.  
This exercise will only focus on one-dimensional arrays (vectors) and two-dimensional arrays (matrices).

[For more information on NumPy](http://www.numpy.org/)

## Prerequisite Skills

- Basic programming concepts
- Lists
- Basic linear algebra concepts

## Exercice 1 

The exercise is composed of several questions.   
To begin, execute the following preamble cell:


In [2]:
import numpy as np

In Python, an array is an ordered collection of values, which can be of any type, not **only numbers**.

The `array()` method allows you to define a **one-dimensional array** from a list. Given `X` as a list of values, you can use the command `np.array(X)` to transform the list into a one-dimensional array.

1. Create an array from the list `[1,1,1,1]`

In [3]:
## Insert your code here
a = np.array([1, 1, 1, 1])

There are commands to inquire about the variables we are manipulating. Here's a table summarizing these commands:

| Command    | Effect                                         | Example                     |
|------------|------------------------------------------------|-----------------------------|
| type(X)    | Returns the type of the variable X            | type(2) returns `<class 'int'>`      |
| np.shape(X)| Returns the dimension of the variable X       | np.shape([1,2]) returns (2,) |

By default, Numpy creates one-dimensional arrays from lists. If you want a different dimension, you should specify it using the command `np.reshape(X, new_shape)` where `X` is the array whose dimensions you want to change.

2. Create a variable *a* and assign to it an array with the list [1,2,3,4,5]
3. Verify that its dimension is indeed (5,)

In [4]:
## Insert your code here
a = np.array([1, 2, 3, 4, 5])
print(a.shape)

(5,)


Now that we've seen how to get information about arrays, we'd like to create some. There are various commands to generate one-dimensional arrays. Here's a table summarizing them:

| Command               | Meaning                                                        | Example                                    |
|-----------------------|----------------------------------------------------------------|--------------------------------------------|
| np.ones(n)            | Returns an array of dimension (n,) of 1s                        | np.ones(5) returns array([1, 1, 1, 1, 1])  |
| np.zeros(n)           | Returns an array of dimension (n,) of 0s                        | np.zeros(5) returns array([0, 0, 0, 0, 0]) |
| np.arange(n)          | Returns an array of dim(n,) of ordered numbers from 0 to n-1    | np.arange(5) returns array([0, 1, 2, 3, 4])|
| np.linspace(a,b,n)    | Returns an array of dim(n,) of n numbers evenly spaced between a and b | np.linspace(0,5,5) returns array([0, 1.25, 2.5, 3.75, 5.0])|
| np.linspace(a,b)      | Returns an array of dim(50,) of 50 numbers evenly spaced between a and b |                                            |
| np.concatenate((X,Y)) | Returns an array of dim(dimX+dimY,) resulting from the assembly of X and Y | np.concatenate((array([1]),array([0]))) returns array([1,0])|

4. Create 4 variables a, b, c, d
    - Assign to a an array with 5 zeros
    - Assign to b an array with 5 ones
    - Assign to c an array of size 10 containing 5 zeros followed by 5 ones, arranged judiciously.
    - Assign to c an array of the integers from 10 to 50.



In [5]:
## Insert your code here
a = np.zeros(5)
print("Array a", a)
b = np.ones(5)
print("Array b", b)
c = np.concatenate((a, b))
print("Array c", c)
d = np.arange(10, 51,)
print("Array d", d)

Array a [0. 0. 0. 0. 0.]
Array b [1. 1. 1. 1. 1.]
Array c [0. 0. 0. 0. 0. 1. 1. 1. 1. 1.]
Array d [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]


5. Generate two arrays of ordered numbers from 0 to 10 (thus of size 11) using different commands.

In [6]:
## Insert your code here
a = np.array(list(range(0, 11)))
print("First method", a)
b = np.arange(0, 11)
print("Second method", b)

First method [ 0  1  2  3  4  5  6  7  8  9 10]
Second method [ 0  1  2  3  4  5  6  7  8  9 10]


6. Create a list `c` with numbers ranging from 0 to 10 **A list, not an array**. 
    - Use the following syntax: `list(range())`.
    - Add 5 to all the terms in `c` 
        - without the numpy library.
        - with the numpy library.
    - Display `c`.


In [9]:
import numpy as np
## Insert your code here
c = list(range(0, 11))
c = [element+5 for element in c]
print("List c", c)

c = list(range(0, 11))
c = np.array(c)
c += 5
print("Array c", c)

List c [5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]
Array c [ 5  6  7  8  9 10 11 12 13 14 15]


We can perform similar operations with matrices, which are 2-dimensional arrays.

Thus, `np.ones((n, p))` returns an `NxP` matrix filled with ones, `np.zeros((n, p))` returns an `NxP` matrix filled with zeros.

`np.diag(v)` returns a matrix whose diagonal consists of the vector v. 
Moreover, `np.diag(v, k)` returns a matrix where the k-th diagonal consists of the vector v, k can be positive or negative; if k is positive, the shift is to the "right," otherwise to the left.

7. Create a matrix *mat* of size 5x5 with 1s on the diagonal.

In [8]:
## Insert your code here
diagonal = np.ones(5)
mat = np.diag(diagonal)
print(mat)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


We can use mathematical operators **+**, **-**, on arrays provided that the mathematical operation makes sense.

**Caution: If you use the operators '\*' or '/' you will only perform a term-by-term operation**  

8. Create a 6x6 matrix with 1s on the diagonal and on the sub-diagonal using a mathematical operator.

In [9]:
## Insert your code here
diagonal = np.ones(6)
sub_diagonal = np.ones(5)

mat = np.diag(diagonal) + np.diag(sub_diagonal, -1)
print(mat)

[[1. 0. 0. 0. 0. 0.]
 [1. 1. 0. 0. 0. 0.]
 [0. 1. 1. 0. 0. 0.]
 [0. 0. 1. 1. 0. 0.]
 [0. 0. 0. 1. 1. 0.]
 [0. 0. 0. 0. 1. 1.]]


Accessing specific elements of an array is done similarly to lists. If the array is two-dimensional, two parameters are needed.

*For example*: let X be a two-dimensional array, `X[0, 0]` returns the element located at row 1, column 1. `X[:, 0]` returns the first column. `X[0:3, 0]` returns the first three rows of the first column. This method is referred to as *slicing* in programming.

9. Create this matrix using `np.ones()`, `np.diag()` and slicing:
$$
\begin{pmatrix}
5 & 0 & 0 & 0 \\
5 & 1 & 0 & 0 \\
4 & 4 & 4 & 4 \\
5 & 0 & 0 & 1
\end{pmatrix}
$$

In [3]:
## Insert your code here
mat = np.zeros((4, 4))
mat[:, 0] = 5
mat[2, :] = 4
mat[1, 1] = 1
mat[3, 3] = 1
print(mat)

[[5. 0. 0. 0.]
 [5. 1. 0. 0.]
 [4. 4. 4. 4.]
 [5. 0. 0. 1.]]


10. Create a numpy array with only ones of shape N, T
11. Using slicing access create :
    - a matrix_a array with all N and T from 0 to 5
    - a matrix_b array with all N and T from T-5 to T-1

In [11]:
N, T = 500, 252
## Insert your code here
mat = np.ones((N, T))
matrix_a = mat[:, 0:5]
print(matrix_a.shape)
matrix_b = mat[:, -5:]
print(matrix_b.shape)

(500, 5)
(500, 5)


## Exercice 2

With the Numpy module, you can create random numbers uniformly distributed between 0 and 1.   
The syntax is as follows: `np.random.rand()` to return a single draw, `np.random.rand(n)` to return a row array of n draws, and `np.random.rand(n, p)` to return an NxP matrix of uniformly distributed random draws.

1. Display a random number uniformly distributed between 0 and 1

In [12]:
## Insert your code here
print(np.random.rand())

0.9628797036569195


2. Display a 5x5 matrix of random numbers uniformly distributed between 0 and 1

In [13]:
## Insert your code here
np.random.rand(5, 5)

array([[0.10587505, 0.52137538, 0.66543042, 0.49282186, 0.13480723],
       [0.82467883, 0.57436591, 0.03961181, 0.91039435, 0.45936421],
       [0.17415153, 0.35017782, 0.07624127, 0.79363371, 0.1610629 ],
       [0.96947943, 0.60309311, 0.01419544, 0.27719202, 0.58230632],
       [0.2867352 , 0.79222053, 0.19855566, 0.71890401, 0.51010199]])

3. Write a function `random_number()` that takes two integer parameters and returns a random number uniformly distributed between the two integers.
4. Call the function `random_number(10, 15)`

*Note: If $X \sim U[0,1]$, then $Y := (b-a)X + a \sim U[a,b]$*

5. Use the function np.rando.uniform to generate a similar variable 

In [14]:
## Insert your code here
def random_number(a:int, b:int):
    return (b-a) * np.random.rand() + a

print(random_number(10, 15))

def random_number(a:int, b:int):
    x = np.random.uniform(a, b)
    return x

10.0313117421264


6. Write a function `random_matrix()` that takes an integer parameter N and returns a NxN matrix with 1s everywhere except on the diagonal where there are numbers uniformly distributed between 0 and 1.
7. Test for N=3 and N=5

> Example: `random_matrix(3)` should return a matrix similar to
$$
\begin{pmatrix}
0.62678954 & 1 & 1 \\
1 & 0.94077299 & 1 \\
1 & 1 & 0.29263003 \\
\end{pmatrix}
$$

In [15]:
## Insert your code here
def random_matrix(N:int)->np.array:
    mat = np.ones((N, N))
    mat[range(N), range(N)] = np.random.uniform(0, 1, size=N)
    return mat 

def random_matrix(N:int)->np.array:
    mat = np.ones((N, N))
    for i in range(N):
        mat[i, i] = np.random.uniform(0, 1)
    return mat 

print(random_matrix(4))

[[0.87672096 1.         1.         1.        ]
 [1.         0.06952482 1.         1.        ]
 [1.         1.         0.0924764  1.        ]
 [1.         1.         1.         0.44208032]]


- In NumPy, operations can be performed between arrays and scalars.
> Example:
```
a = np.array([1, 2, 3])
a * 4 returns array([4, 8, 12])
a + 2 returns array([3, 4, 5])
```

8. Create a matrix mat_five of size 5x5 with fives on the diagonal
9. Create two matrices mat_two and mat_two_bis of size 5x5 with twos everywhere, in two different ways
    - Use a list by comprehension in one method
10. Display the matrices

In [16]:
## Insert your code here
mat_five = np.identity(5)*5

mat_two = np.array([2 for _ in range(5)])
mat_two = np.diag(mat_two)

mat_two_bis = np.array([[2 if i == j else 0 for j in range(5)] for i in range(5)])

print(mat_five)
print(mat_two)
print(mat_two_bis)

[[5. 0. 0. 0. 0.]
 [0. 5. 0. 0. 0.]
 [0. 0. 5. 0. 0.]
 [0. 0. 0. 5. 0.]
 [0. 0. 0. 0. 5.]]
[[2 0 0 0 0]
 [0 2 0 0 0]
 [0 0 2 0 0]
 [0 0 0 2 0]
 [0 0 0 0 2]]
[[2 0 0 0 0]
 [0 2 0 0 0]
 [0 0 2 0 0]
 [0 0 0 2 0]
 [0 0 0 0 2]]


In NumPy, operations between arrays are performed element-wise by default.

> Example:
```
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
a * b returns array([4, 10, 18])
```

To perform matrix multiplication in the mathematical sense, the following syntax is used: np.dot(X,Y)

If the dimensions are incompatible, errors are triggered.

## Exercice 3

1. Create a matrix `mat_one` of size 5x5 with random numbers.
2. Create a matrix `mat_two` of size 5x5 with ones everywhere.
3. Create a matrix `mat_three` and assign to it the element-wise product between `mat_one` and `mat_two`
4. Create a matrix mat_four and assign to it the matrix product between `mat_one` and `mat_two`
5. Display `mat_three` and `mat_four`

In [17]:
## Insert your code here
mat_one = np.random.uniform(-1, 1, size=(5, 5))
mat_two = np.ones(shape=(5, 5))
mat_three = mat_one * mat_two
mat_four = np.matmul(mat_one, mat_two)
print(mat_three)
print(mat_four)

[[-0.60998043  0.23092791  0.93527846  0.51144992  0.31260504]
 [ 0.05682331  0.4262      0.2407506  -0.72673372 -0.97075194]
 [-0.57945962  0.74044601  0.72833747  0.36828509 -0.74469167]
 [ 0.76801387  0.79963871  0.67347971  0.98981945  0.38200851]
 [-0.23966003  0.42311439 -0.66580852 -0.14907656  0.22572185]]
[[ 1.38028091  1.38028091  1.38028091  1.38028091  1.38028091]
 [-0.97371175 -0.97371175 -0.97371175 -0.97371175 -0.97371175]
 [ 0.51291729  0.51291729  0.51291729  0.51291729  0.51291729]
 [ 3.61296024  3.61296024  3.61296024  3.61296024  3.61296024]
 [-0.40570887 -0.40570887 -0.40570887 -0.40570887 -0.40570887]]



6. Create a matrix `a` with dimensions 5x2 with arbitrary values
7. Create another matrix `b` with dimensions 2x5 with arbitrary values
8. Return the [Hadamard product](https://en.wikipedia.org/wiki/Hadamard_product_(matrices)) of the two matrices here



In [18]:
## Insert your code here
a = np.random.uniform(10, 11, size=(5, 2))
b = np.random.uniform(-10, -9, size=(2, 5))
print(a * b.T)

[[-102.29524622  -95.52405278]
 [-100.35600367  -99.09655269]
 [ -95.78157398 -106.41618788]
 [ -94.057916   -101.90510451]
 [-101.81900611 -102.30350161]]


## Exercice 4

The use of logical operators is possible via NumPy.

1. Create two matrices *mat_one* and *mat_two* of size 5x5 with random values.
2. Using the operator `*` and the logical operator '`==`', return a 5x5 matrix of True.
3. Using matrix multiplication and the logical operator '`==`', return a 5x5 matrix of False.


In [19]:
## Insert your code here
mat_one = np.random.uniform(-1, 1, size=(5, 5))
mat_two = np.random.uniform(-1, 1, size=(5, 5))

print(
    mat_one * mat_two == mat_two * mat_one
    )

print(
    np.matmul(mat_one, mat_two) == np.matmul(mat_two, mat_one)
)

[[ True  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]]
[[False False False False False]
 [False False False False False]
 [False False False False False]
 [False False False False False]
 [False False False False False]]


## Exercice 5

It is possible to analyze data with NumPy. Here are some functions summarized:

| Command   | Meaning                 |
|-----------|-------------------------|
| np.mean(X) | returns the mean of X   |
| np.var(X)  | returns the variance of X|
| np.std(X)  | returns the standard deviation of X |
| X.sum()  | sums the elements of X   |
| X.prod() | multiplies the elements of X |
| X.min()  | returns the minimum of X |
| X.max()  | returns the maximum of X |

Furthermore, when working with matrices, it's possible to specify a second argument or a parameter to clarify where we are working. For example:

```
mat = np.random.rand(5, 5)
np.mean(mat, axis = 0)  ## returns the mean of the rows
np.mean(mat, axis = 1) ## returns the mean of the columns
mat.sum(axis = 0) ## returns the sum of the rows
```

1. Verify that the mean of a uniformly distributed law on [0,1] is close to 0.5 for a large number of draws. 

**Note:**

*As the number of draws increases, the mean value of the uniformly distributed random values should converge to 0.5 according to the Law of Large Numbers.*

In [20]:
## Insert your code here
def mean_approximation(n):
    return np.random.uniform(0, 1, size=n).mean()

from tqdm import tqdm

for k in tqdm(range(1, 11)):
    n = 100 * k
    print(f"Error with n = {n} is {mean_approximation(n)-0.5}")

100%|██████████| 10/10 [00:00<00:00, 5014.11it/s]

Error with n = 100 is 0.022649822646442996
Error with n = 200 is -0.01905372858759441
Error with n = 300 is -0.05296456455530535
Error with n = 400 is -0.01395904606883469
Error with n = 500 is 0.0033162949462834934
Error with n = 600 is -0.004525925196070368
Error with n = 700 is 0.005880769838557676
Error with n = 800 is -0.016859846605157935
Error with n = 900 is -0.009368862135345435
Error with n = 1000 is 0.002685893301579867


2. Approximate $\pi$ using the folowing equation, using only Numpy methods and a function
$$
\frac{\pi}2=\prod_{n=1}^{\infty}\frac{4n^2}{4n^2-1}
$$
```python 
def pi_approximation(n)
    ...
    return approx
``` 

3. Compare using `np.math.pi` for different values of n using 

```python 
from tqdm import tqdm 
for n in tqdm(range(1, 100, 10)):
```

In [21]:
## Insert your code here
def pi_approximation(n:int)->float:
    approx = [4*k**2 / (4*k**2 - 1) for k in range(1, n)]
    approx = np.prod(approx)
    return 2*approx

for n in tqdm(range(1, 100, 10)):
    print(f"Error with n = {n} is {pi_approximation(n)-np.pi}")

100%|██████████| 10/10 [00:00<00:00, 2499.88it/s]

Error with n = 1 is -1.1415926535897931
Error with n = 11 is -0.0738888469462946
Error with n = 21 is -0.03807569205056005
Error with n = 31 is -0.025644367701834536
Error with n = 41 is -0.019332327168355867
Error with n = 51 is -0.015513753374382322
Error with n = 61 is -0.012954855698201762
Error with n = 71 is -0.011120577270728571
Error with n = 81 is -0.009741302217184167
Error with n = 91 is -0.008666412962285097


## To go further..

**Exercise :**
- Create a 3x3 matrix with values ranging from 0 to 8 using `np.reshape`.
- Create a 3x3 identity matrix with a built in numpy function.
- Use indexing to replace the top row of the identity matrix with 9s. Make sure not to modify the initial matrix.

**Exercise :**
- Generate a random array of size 25, folowing a normal distribution. Find its mean.
- Generate a random matrix of size 5x5. Find the sum of all the elements, the sum of the columns, and the sum of the rows.

**Exercise :**
- Create an array of 10 random numbers. Replace all the values less than 0.5 with 0.

**Exercise :**
- Using np.random.uniform estimate the value of pi.

**Hint:** Use the probability of a random point $X = (x_1, x_2)$ with $X \in [-1, 1]^2$ to belong to the unit circle.

**Exercise :**

This exercie aims to illustrate the difference in computation between Python `list` and `NumPy` arrays.

1. Create a Python `my_list` of 100 000 integers using `range`.
2. Create a Python `my_array` of 100 000 integers using `np.arange`.
3. Compute the sum of all elements:
   - Using the built-in `sum()` function on the Python list.
   - Using the `np.sum()` function on the NumPy array.
4. Compare the execution times of the two approaches.

**Hint:** Use the `%timeit` magic command in a Jupyter notebook or the `time` module in Python to measure performance (only when computing the sum).

``` python
%timeit sum(py_list)
```

In [22]:
## Insert your code here
mat = np.arange(0, 9)
mat = np.reshape(mat, newshape=(3, 3))
print(mat)

identity = np.identity(3)
print(identity)

new_mat = np.copy(identity)
new_mat[0, :] = 9
print(new_mat)
print(identity)

print(np.random.normal(size=25).mean())

mat = np.random.uniform(-9, 9, size=(5, 5))
print(mat.sum())
print(mat.sum(axis=0))
print(mat.sum(axis=1))

mat = np.random.uniform(0, 1, size=10)
print(mat)
mat[mat < 0.5] = -1
print(mat)

def pi_approximation(n_samples:int):
    samples = np.random.uniform(-1, 1, size=(2, n_samples))
    samples = samples ** 2
    squarre_distance_to_center = samples.sum(axis=0)
    is_in_unit_circle = squarre_distance_to_center <= 1
    approx = is_in_unit_circle.mean() * 4
    return approx

print(pi_approximation(100))
print(pi_approximation(1000))
print(pi_approximation(10000))

my_list = [k for k in range(100000)]
%timeit sum(my_list) / len(my_list)
my_array = np.arange(100000)
%timeit np.mean(my_array)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[9. 9. 9.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
-0.21605340617814173
-46.75523835384017
[-24.07912324  -3.30440363   6.14573239 -18.01821899  -7.49922487]
[-15.91272108  -0.77060388 -10.28658125  -5.76197769 -14.02335445]
[0.63636549 0.18511469 0.96463824 0.65297814 0.02611766 0.40898013
 0.85526836 0.92264248 0.73681478 0.30850488]
[ 0.63636549 -1.          0.96463824  0.65297814 -1.         -1.
  0.85526836  0.92264248  0.73681478 -1.        ]
3.28
3.164
3.1196


2.53 ms ± 168 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
138 µs ± 62 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)
